# Generated by Django 3.1.4 on 2020-12-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_category', models.CharField(choices=[('Latest', 'LATEST'), ('Featured', 'FEATURED')], default='', max_length=50)),
                ('news_title', models.CharField(default='', max_length=50)),
                ('news_desc', models.TextField(default='')),
                ('news_image', models.ImageField(null=True, upload_to='mycsi/images')),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
