# Generated by Django 3.1.4 on 2020-12-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='Destination_category',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='contact_num1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='contact_num2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sport_category',
        ),
        migrations.AddField(
            model_name='tournament',
            name='event_category',
            field=models.CharField(choices=[('IBSF', 'IBSF'), ('ACBS', 'ACBS'), ('National', 'NATIONAL'), ('Invitation', 'INVITATION'), ('Open Entry', 'OPEN ENTRY'), ('Professional', 'PROFESSIONAL')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sports_category',
            field=models.CharField(choices=[('Billiards', 'BILLIARDS'), ('ACBS', 'ACBS'), ('Snooker', 'SNOOKER'), ('6RED', '6RED'), ('Pool', 'POOL'), ('Carrom', 'CARROM')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_image2',
            field=models.ImageField(blank=True, upload_to='tournament/images'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='paytm_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_image1',
            field=models.ImageField(upload_to='tournament/images'),
        ),
    ]
