# Generated by Django 3.1.4 on 2020-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20201217_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sports_category',
            field=models.CharField(choices=[('Billiards', 'BILLIARDS'), ('Snooker', 'SNOOKER'), ('6Reds', '6REDS'), ('10Reds', '10REDS'), ('Pool', 'POOL'), ('Carrom', 'CARROM')], default='', max_length=50),
        ),
    ]
