# Generated by Django 3.1.4 on 2020-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Banner', models.ImageField(upload_to='home/images')),
                ('url', models.URLField()),
            ],
        ),
    ]
